# Generated by Django 6.0.1 on 2026-01-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LEADER', 'Youth Leader'), ('MENTOR', 'Mentor'), ('MEMBER', 'Youth Member'), ('VOLUNTEER', 'Volunteer'), ('GUEST', 'Guest')], default='MEMBER', max_length=20),
        ),
    ]
