# Generated by Django 6.0.1 on 2026-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='REGISTERED', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual')], default='PHYSICAL', max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(help_text='Physical location or Virtual meeting link', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
